#!/usr/bin/env bash
pip3 install Fabric
sudo apt-get install libffi-dev
sudo apt-get install libssl-dev
sudo apt-get install build-essential
sudo apt-get install python3.4-dev
sudo apt-get install libpython3-dev
pip3 install --force-reinstall pyparsing
pip3 install --force-reinstall appdirs
pip3 install --force-reinstall setuptools==40.1.0
pip3 install --force-reinstall cryptography==2.8
pip3 install --force-reinstall bcrypt==3.1.7
pip3 install --force-reinstall PyNaCl==1.3.0
pip3 install --force-reinstall Fabric3==1.14.post1
